export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAILED = 'FACEBOOK_LOGIN_FAILED';

export const USER_ALREADY_LOGGED_IN = 'USER_ALREADY_LOGGED_IN';
export const USER_ALREADY_NOT_LOGGED_IN = 'USER_ALREADY_NOT_LOGGED_IN';

export const FETCH_JOBS = 'FETCH_JOBS';
export const LIKE_JOB = 'LIKE_JOB';
export const CLEAR_LIKED_JOBS = 'CLEAR_LIKED_JOBS';